Repository SuffolkLITLab/docassemble-CivilActionCoverSheet, pull requests merged in 2020-08, with the labels that each got.

#28 CACS Issue 12
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: language fix

#37 Language fix: CACS Issue 20
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: language fix

#36 CACS Issue 18
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: language fix

#25 Cacs issue 11
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: easy fix

#38 Issue #26: Fixed language on contract claims
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: language fix

#44 Simplify attorney representation question
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: easy fix, language fix
