Repository SuffolkLITLab/docassemble-CivilActionCoverSheet, pull requests merged in 2020-10, with the labels that each got.

#79 Override other party name basic question
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: showstopper

#81 Removes bold typeface from question seeking defendant's name
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: enhancement

#83 Change 'plaintiff' to 'your client' in attorney name question
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: enhancement

#85 Simplify question asking attorney's name
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: language fix

#88 Fix issue where other documented damages description didn't print to pdf
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: bug

#90 Makes the send to court button conditional
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: enhancement
