Repository SuffolkLITLab/docassemble-CivilActionCoverSheet, pull requests merged in 2020-09, with the labels that each got.

#45 Opened up spacing on page id: download form
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: easy fix

#48 Stop any other users question triggering
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: bug, invalid

#52 Insert conditional language to ask user's address (attorney or plaintiff user)
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: language fix

#54 Insert conditional language to ask user's name (attorney or plaintiff user)
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: language fix

#58 Fix signature date behavior
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: bug

#56 Customize attorney address question to override basic question
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: language fix

#55 Fix related actions question
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: bug

#61 Fixed missing BBO number on PDF
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: bug

#63 Interview now asks for Plaintiff's address
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: bug

#69 Ask track designation before questions pertaining to your case
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: enhancement

#64 Sets currency fields at no decimal points
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: bug

#72 Fix preview screen language
  docassemble/CivilActionCoverSheet/data/questions/Civil_Action_Cover_Sheet.yml
Labels: language fix
